### ISSUE TITLE
3D Renderer Roadmap

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#4]
# Short Term

- [x] Optimized WebGL engine derived from xeogl
- [ ] Large-scale rendering with instancing and batching - in progress
- [ ] Geometries created from pre-compressed geometry arrays - in progress
- [ ] Shadows
- [ ] 3D picking with purely GPU-resident geometry 
- [ ] Draco compression support in glTF 

# Long Term

- [x] WebGPU-based 3D renderer
