### ISSUE TITLE
BIM Roadmap

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#5]
#   BIMServer

- [x] Download from BIMserver 1.5.120, protocol version >= 17
- [ ] Download quantized geometry from BIMServer - in progress
- [ ] Massive model support - in progress
- [ ] Utility for downloading IFC from BIMServer as JSON for offline BIM - in progress

# BIM Offline

- [x] Massive model support - in progress

# Plugins

- [x] BIMServerLoaderPlugin
- [x] GLTFModelsPlugin
- [x] BCFViewpointsPlugin
- [ ] BIMPlanViewPlugin

**Comment by sha-N** [comment]
Hi, I was checking out this SDK to replace with BIMSURFER, Great Job 👍. 

But Im facing an issue, the plugin loads structural IFC files properly, but for IFC files containing pipes or those type of geometries, the objects looks pixelated and is shaking while moving the camera. 

Does this has anything to do with the plugin being based on PerformanceModel.

Is this being worked on?
![capture](https://user-images.githubusercontent.com/12491622/52964118-9cd65c00-33b2-11e9-8950-97796dbe9fef.PNG)

**Comment by xeolabs** [comment]
Hi, thanks. Could you repost this as it's own issue? Then I'll add some comments to that issue.

**Comment by sha-N** [comment]
> Hi, thanks. Could you repost this as it's own issue? Then I'll add some comments to that issue.

Yes of course
