### ISSUE TITLE
Touch support for DistanceMeasurementsPlugin and AngleMeasurementsPlugin

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#816]
Make the measurement tools work for touch input.

![63047331-867a0a80-bed4-11e9-892f-398740013c5f](https://user-images.githubusercontent.com/83100/179097220-7ced35ee-2abe-4c51-96de-ae267d9e3635.gif)

## Subtasks

- [x]  Add touch support for [DistanceMeasurementsPlugin](https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/DistanceMeasurementsPlugin/DistanceMeasurementsPlugin.js~DistanceMeasurementsPlugin.html)
- [x] Add touch support for [AngleMeasurementsPlugin](https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/AngleMeasurementsPlugin/AngleMeasurementsPlugin.js~AngleMeasurementsPlugin.html)
- [x] Precision-mode for touch

## Demos

- [Create distance measurements with mouse/touch](https://xeokit.github.io/xeokit-sdk/examples/#measurements_distance_createWithMouse)
- [Create angle measurements with mouse/touch](https://xeokit.github.io/xeokit-sdk/examples/#measurements_angle_createWithMouse)
